### PR TITLE
310p export bug fix

### PR DESCRIPTION
**Pull request by kk928290341**
Thank you for your contribution to the MindOCR repo.
Before submitting this PR, please make sure:

- [x] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved terminology
- [x] You have added unit tests

## Motivation
310p机器ocr检测和识别模型 全量export，发现可修复的bug
1. crnn_resnet34_ch convert shape匹配不上
2. 文件存在时remove报错
3. Abinet, svtr_tiny export失败解决：
    (1) 有些ms版本在init里不能有tensor操作，一般是要先用numpy算好，再转成Tensor
    (2)矩阵乘维度对不上，没有自动广播

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by horcham** [comment]
涉及算子修改，需复验精度

rec类模型(例如svtr_tiny)，验证精度用这个脚本：
python tools/benchmarking/multi_dataset_eval.py --config configs/rec/svtr/svtr_tiny.yaml

det类模型（例如dbnet_r50)，是
python tools/eval.py --config configs/det/dbnet/db_r50_icdar15.yaml

**Comment by kk928290341** [comment]
你发的邮件我已收到，谢谢

**Comment by kk928290341** [comment]
复验精度
abinet 平均acc=91.35%
svtr-tiny 平均acc=90.25%
达标

**Comment by Mark-ZhouWX** [comment]
右上角修改一下Reviewers

**Review by Mark-ZhouWX — COMMENTED** [review]
approve

**Review by horcham — APPROVED** [review]

**Comment by kk928290341** [comment]
你发的邮件我已收到，谢谢

**Review by Mark-ZhouWX — APPROVED** [review]

**Pull request merged**
