### PR TITLE
update Fce loss ops.matmul with float16

### PR DESCRIPTION
**Pull request by colawyee**
Thank you for your contribution to the MindOCR repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

### CODE REVIEW

**Comment by HaoyangLee** [comment]
Does the performance improved due to this change?

**Comment by hadipash** [comment]
> Does the performance improve due to this change?

Significantly. This is before:
image

After:
image

Execution time of `MatMul` decreased from 12,596 ms per epoch down to 1.6 ms per epoch.

**Comment by HaoyangLee** [comment]
Incredible result! Do you find the root cause or any materials related to why ops.matmul perform significanly better in fp16 than fp32? Wanna learn more about this :)

**Comment by HaoyangLee** [comment]
BTW, report the fps and ms/step in readme and [modelzoo](https://github.com/mindspore-lab/mindocr/blob/main/docs/en/mkdocs/modelzoo_training.md), and can try full training later to check whether the fp16 change here will affect the fscore a lot.

**Review by SamitHuang — APPROVED** [review]

**Pull request merged**
